keys:
  - &htpc   age12v2trr3z00pyh3g7z5u32rcgethgu4vhfw8ssnlkmeknjpeqhcas95ac9x
  - &laptop age1zr8f9768vjzw0h37jgsf74xr27tznpe56v7degu427qzve0wlcysazds94

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *htpc
          - *laptop
