[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 5
snippets_first = true
feature_words = true
feature_snippets = true
feature_unicode_input = true

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true


[[language]]
name = "typescript"
language-servers = [ "scls", "typescript-language-server", "eslint" ]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "ts" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "scls", "typescript-language-server", "eslint" ]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "tsx" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "scls", "typescript-language-server", "eslint" ]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "scls", "typescript-language-server", "eslint"  ]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "jsx" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server" ]
formatter = { command = 'prettierd', args = ["--parser", "html"] }
auto-format = false

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
formatter = { command = 'prettierd', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]
